### ISSUE TITLE
Individual elements

### ISSUE THREAD

**Issue by NekR** [WICG/user-gesture-nav#3]
Is this property mean to be applied to individual elements or it will affect only the viewport?

**Comment by majido** [comment]
It is meant to be applied on viewport only. However we have decided to abandon this proposal in favor of `scroll-boundary-behavior` API ([proposal](https://discourse.wicg.io/t/generic-scroll-chaining-prevention-mechanism-or-expand-standardize-ms-scroll-chaining/1811), [draft spec](https://wicg.github.io/scroll-boundary-behavior/)) which can address the same usecase in a simpler and more generic fashion.

**Comment by NekR** [comment]
Okay, thank you :-)
